config/routes.rb
Rails.application.routes.draw do

  root 'flights#index'

  resources :flights,  only: [:index, :show]
  resources :bookings, only: [:new, :create, :show]

end

app/models/airline.rb
class Airline < ApplicationRecord
  # Relationships
  has_many :flights
  
  
end

app/models/airport.rb
class Airport < ApplicationRecord
  # Relationships
  has_many :departures, class_name: 'Flight', foreign_key: :departure_airport_id
  has_many :arrivals, class_name: 'Flight', foreign_key: :destination_airport_id
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  # Relationships
  belongs_to :flight
  has_many :passenger_bookings
  has_many :passengers, through: :passenger_bookings

  accepts_nested_attributes_for :passengers,
    reject_if: lambda { |attributes| attributes['name'].blank? }

end

app/models/flight.rb
class Flight < ApplicationRecord
  attr_reader :duration
  
  # Relationships
  belongs_to :airline
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :destination_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings
  
  # Alias
  alias_attribute :from_airport, :departure_airport
  alias_attribute :to_airport,   :destination_airport
  
  # Return flight duration (string)
  def duration
    humanize (arrival - departure)
  end
  
  # Returns flight number with airline name
  def full_flight_number
    "#{airline.name} #{flight_number}"
  end
  
  # Returns flight number with airline short_code
  def short_flight_number
    "#{airline.short_code}#{flight_number}"
  end

  def self.available_dates
    flights = Flight.all.order(departure: :asc)
		flights.map { |flight| flight.departure.strftime("%Y/%m/%d") }.uniq
  end
  
  def self.search(search_params)
    d_date = Date.parse(search_params[:departure])
    Flight.where(departure_airport: search_params[:departure_airport],
                 destination_airport: search_params[:destination_airport],
                 departure: d_date.beginning_of_day..d_date.end_of_day)
  end
  
  private
  
    def humanize secs
      [[60, :seconds], [60, :minutes], [24, :hours], [1000, :days]].map{ |count, name|
        if secs > 0
          secs, n = secs.divmod(count)
          "#{n.to_i} #{name}"
        end
      }.compact.reverse.join(' ')
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  # Relationships
  has_many :passenger_bookings
  has_many :bookings, through: :passenger_bookings
  has_many :flights, through: :bookings

  validates :name, presence: true
end

app/models/passenger_booking.rb
class PassengerBooking < ApplicationRecord
  # Relationships
  belongs_to :passenger
  belongs_to :booking

  accepts_nested_attributes_for :passenger

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show]
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight])
    num_passengers = params[:num_passengers].to_i
    num_passengers.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.create(booking_params)
    params[:booking][:passengers_attributes].each do |passenger|
      @booking.passengers.create(name: passenger["name"])
    end
    redirect_to @booking
  end

  def show
  end

  private

    def booking_params
      params.require(:booking).permit(:flight_id,
                                      passengers_attributes: [ :passenger_id, :name ])

    end

    def set_booking
      @booking = Booking.find(params[:id])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: :show

  def index
    @airports_options = Airport.all.map { |ap| [ap.iata, ap.id] }
    @dates = Flight.available_dates

    if params[:commit]
      unless validate_params
        redirect_to root_url
        return
      end
      @flights = Flight.search(search_params)
    end

  end

  def show
  end

  private

    def search_params
      params.permit(:departure_airport, :destination_airport, :departure,
                    :num_passengers)
    end

    def validate_params
      case
      when params[:departure_airport].empty?
        flash[:warning] = "No departure airport selected."
        return false
      when params[:destination_airport].empty?
        flash[:warning] = "No destination airport selected."
        return false
      when params[:departure_airport] == params[:destination_airport]
        flash[:warning] = "Departure airport and destionation airport is the same."
        return false
      when params[:departure].empty?
        flash[:warning] = "Please select a departure date."
        return false
      else
        return true
      end
    end

    def set_flight
      @flight = Flight.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <div class="col">
        <%= @flight.full_flight_number %>
      </div>
      <div class="col">
        From: <%= @flight.departure_airport.name %>
      </div>
      <div class="col">
        To: <%= @flight.destination_airport.name %>
      </div>
    </div>
    <div class="col-6">
      <div class="col">
        Take-off: <%= @flight.departure %>
      </div>
      <div class="col">
        Landing: <%= @flight.arrival %>
      </div>
      <div class="col">
        Duration: <%= @flight.duration %>
      </div>
    </div>
  </div>
  <br>
  <h4>Passenger Information</h4>
  <%= form_for @booking do |f| %>
    <%= f.hidden_field :flight_id, value: @flight.id %>

    <%= f.fields_for :passengers do |passenger| %>
      <div class="form-group">
        <%= passenger.label :name, "Passenger Name:" %>
        <%= passenger.text_field :name, class: "form-control" %>
      </div>
    <% end %>

    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h2>Information for Booking #<%= @booking.id %></h2>

  <div class="row">
    <div class="col-6">
      <div class="col">
        <%= @booking.flight.full_flight_number %>
      </div>
      <div class="col">
        From: <%= @booking.flight.departure_airport.name %>
      </div>
      <div class="col">
        To: <%= @booking.flight.destination_airport.name %>
      </div>
    </div>
    <div class="col-6">
      <div class="col">
        Take-off: <%= @booking.flight.departure %>
      </div>
      <div class="col">
        Landing: <%= @booking.flight.arrival %>
      </div>
      <div class="col">
        Duration: <%= @booking.flight.duration %>
      </div>
    </div>
  </div>

  <br>

  <h4>Passenger Information:</h4>
  <div class="row">
    <div class="col">
      <% @booking.passengers.each_with_index do |p, idx| %>
        <p>Passenger #<%= idx + 1%>: <%= p.name %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/flights/_result.html.erb
<%= form_tag(new_booking_path, method: :get) do %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Select Flight</th>
        <th>Flight No.</th>
        <th>Airline</th>
        <th>Depart From</th>
        <th>Destionation</th>
        <th>Depature</th>
        <th>Arrival</th>
      </tr>
    </thead>
    <tbody>
      <% @flights.each do |f| %>
        <tr>
          <td class="text-center"><%= radio_button_tag(:flight, f.id) %></td>
          <td>
            <%= link_to f.short_flight_number, f %>
          </td>
          <td><%= f.airline.name %></td>
          <td><%= f.departure_airport.name %></td>
          <td><%= f.destination_airport.name %></td>
          <td><%= f.departure.strftime("%m/%d %I:%M%p") %></td>
          <td><%= f.arrival.strftime("%m/%d %I:%M%p") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= hidden_field_tag(:num_passengers, params[:num_passengers]) %>

  <div class="row">
      <%= submit_tag("Next", class: "btn btn-block btn-success align-right") %>
  </div>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_tag("/", method: :get, class: 'form-inline' ) do %>

  <%= select_tag(:departure_airport, 
                 options_for_select(@airports_options), 
                 class: "form-control col mb-2 mr-sm-2 mb-sm-0",
                 prompt: 'Departure Airport') %>
  
  <%= select_tag(:destination_airport, 
                 options_for_select(@airports_options), 
                 class: "form-control col mb-2 mr-sm-2 mb-sm-0",
                 prompt: 'Destination Airport') %>

  <%= select_tag(:departure,
                 options_for_select(@dates),
                 class: "form-control col mb-2 mr-sm-2 mb-sm-0",
                 prompt: "Departure Date") %>
                 
  <%= select_tag(:num_passengers,
                 options_for_select((1..5).to_a),
                 class: "form-control col mb-2 mr-sm-2 mb-sm-0",
                 prompt: "Num. of Passengers") %>
  
  <%= submit_tag("Search", class: "btn btn-primary") %>



<% end %>

app/views/flights/index.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="row">
      <div class="col">
        <%= render 'flights/search_form' %>
      </div>
    </div>
  </div>
  
  <% if @flights && @flights.empty? %>
    <div class="col-md-6">
      <p>No result!</p>
    </div>
  <% elsif @flights.present? %>
    <%= render 'flights/result' %>
  <% end %>
</div>

app/views/flights/show.html.erb
<div class="container">

  <div class="row">
    <div class="col">
      <h1><%= @flight.full_flight_number %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <b>From: </b><%= @flight.departure_airport.name %> |
                   <%= @flight.departure_airport.iata %> |
                   <%= @flight.departure_airport.city %>
    </div>
    <div class="col-6 text-right">
      <b>Depart: </b><%= @flight.departure %>
    </div>
    <div class="col-6">
      <b>To: </b><%= @flight.destination_airport.name %> |
                   <%= @flight.destination_airport.iata %> |
                   <%= @flight.destination_airport.city %>
    </div>
    <div class="col-6 text-right">
      <b>Arrival: </b><%= @flight.arrival %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col">
      <h5>Passengers</h5>
      <% if @flight.passengers.empty? %>
        <p>No Passenger</p>
      <% else %>
        <table class="table table-hover">
          <thead>
            <tr>
              <td>Name</td>
              <td>Booking Number</td>
            </tr>
          </thead>
          <tbody>
            <% @flight.passengers.each do |p| %>
              <tr>
                <td><%= p.name %></td>
                <th><%= p.bookings.where(flight_id: @flight.id).first.id %></th>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/_bootstrap.html.erb
<%= stylesheet_link_tag    'https://cdn.jsdelivr.net/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'https://cdn.jsdelivr.net/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js',
                           'data-turbolinks-track': 'reload' %>

app/views/layouts/_flash.html.erb
<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: ["alert", "alert-" + message_type] %>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<div class="container">
  <nav class="navbar navbar-inverse bg-inverse rounded navbar-toggleable-md">
    <button class="navbar-toggler navbar-toggler-right" type="button"
            data-toggle="collapse" data-target="#containerNavbar"
            aria-controls="containerNavbar" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= link_to "Flight Booker", root_url, class: "navbar-brand" %>
  </nav>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flight Booker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/bootstrap' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/flash' %>
    <br>
  </body>
</html>